services:
    server:
        build:
            context: .
        ports:
            - 80:80
        networks:
            - test_network

networks:
    test_network:
        external: true
        name: test_network
